src/dbusservice/com.deepin.Home.Daemon.xml, src/main/daemon.cpp, src/main/homeDaemon.cpp, src/main/homeDaemon.h, src/maincomponentplugin/api/API.qml, src/maincomponentplugin/index/Index.qml, src/maincomponentplugin/titlebar/MyTitleBar.qml, src/maincomponentplugin/worker.cpp, src/maincomponentplugin/worker.h, translations/deepin-home-daemon.ts, translations/deepin-home-daemon/az.ts, translations/deepin-home.ts, translations/deepin-home/az.ts, translations/deepin-home/sq.ts, translations/deepin-home/zh_CN.ts, translations/deepin-home/zh_HK.ts, translations/deepin-home/zh_TW.ts
=> feat: add autostart switch

src/main/CMakeLists.txt, src/maincomponentplugin/index/Card1.qml, src/maincomponentplugin/index/Card2.qml, src/maincomponentplugin/index/Carousel.qml, src/maincomponentplugin/index/Index.qml, src/maincomponentplugin/list/Notify.qml, src/maincomponentplugin/list/Questionnaire.qml, src/maincomponentplugin/main.qml, src/maincomponentplugin/titlebar/MyTitleBar.qml
修复在暗黑主题显示问题
优化可点击组件的鼠标样式
优化轮播图显示效果
Log: 修复样式问题
=> fix: display in dark theme

deepin-home.desktop, src/main/homeDaemon.cpp, src/preloadplugin/Preload.qml, translations/deepin-home-daemon/pt.ts, translations/deepin-home/ca.ts, translations/deepin-home/de.ts, translations/deepin-home/el.ts, translations/deepin-home/hu.ts, translations/deepin-home/nl.ts, translations/deepin-home/pl.ts, translations/deepin-home/pt.ts, translations/deepin-home/uk.ts
=> feat: change name of the desktop file

.reuse/dep5, .tx/deepin.conf, CMakeLists.txt, debian/changelog, src/main/daemon.cpp, src/maincomponentplugin/api/API.qml, src/maincomponentplugin/titlebar/MyTitleBar.qml, src/maincomponentplugin/worker.cpp, src/maincomponentplugin/worker.h, src/preloadplugin/preloadplugin.cpp, translations/deepin-home-daemon/zh_CN.ts, translations/deepin-home-daemon/zh_HK.ts, translations/deepin-home-daemon/zh_TW.ts, translations/deepin-home/zh_CN.ts, translations/deepin-home/zh_HK.ts, translations/deepin-home/zh_TW.ts
从changelog读取应用版本号,实现自动更新版本显示
更新翻译
=> read app version info from changelog

src/maincomponentplugin/list/Questionnaire.qml
=> feat: questionnaire summary show two lines

src/maincomponentplugin/index/Carousel.qml, src/maincomponentplugin/titlebar/MyTitleBar.qml
修复轮播图和url关联错误
修复菜单中开关自启动英文环境显示不全
Log:
=> fix: open the wrong link when click carousel

src/main/daemon.cpp
添加AA_EnableHighDpiScaling以支持高分辨率显示
Log:
=> feat: support high dpi

.obs/workflows.yml, .reuse/dep5
=> feat: add obs workflow

.gitignore, CMakeLists.txt, debian/changelog, src/main/daemon.cpp, src/main/main.cpp, src/preloadplugin/preloadplugin.cpp
=> fix: about dialog in dark theme

.gitignore, CMakeLists.txt, debian/rules, src/main/daemon.cpp, src/preloadplugin/preloadplugin.cpp
构建deb包未传递版本信息,导致关于对话框的版本显示异常
Log:
=> fix: dpkg build version error

src/dbusservice/com.deepin.Home.Daemon.xml, src/main/homeDaemon.cpp, src/main/homeDaemon.h, src/main/main.cpp, src/maincomponentplugin/api/API.qml, src/maincomponentplugin/index/Index.qml, src/maincomponentplugin/worker.cpp, src/maincomponentplugin/worker.h
点击系统托盘或使用托盘菜单时,激活被最小化的主窗口
Log: "显示主窗口"按钮激活最小化的主窗口
Bug: https://pms.uniontech.com/bug-view-182277.html
=> fix: Activate minimized window when tray is cliced

src/preloadplugin/Preload.qml
=> fix: The minimum window height is not set

src/maincomponentplugin/article/Article.qml, src/maincomponentplugin/network.cpp
InWindowBlur的radius参数无效,导致对话框的圆角异常
Log: 修复内测交流对话框的圆角显示问题
Bug: https://pms.uniontech.com/bug-view-182717.html
=> fix: dialog rounded corners not working

src/main/homeDaemon.cpp
Link issuse: https://github.com/linuxdeepin/developer-center/issues/3605
=> fix: 解决在系统托盘中的右键菜单bug

.tx/config, src/maincomponentplugin/index/Index.qml, src/maincomponentplugin/main.qml, translations/deepin-home-daemon.ts, translations/deepin-home.ts
在离线提示页面添加刷新按钮
close linuxdeepin/developer-center#3799
=> feat: add page refresh button

.obs/workflows.yml
obs build use beige develop repo
=> chore(CI): change obs workflow

src/main/CMakeLists.txt
=> chore: Invalid qrc path

src/maincomponentplugin/main.qml
重构代码时,托盘激活窗口的功能丢失了
Fix 
- https://github.com/linuxdeepin/developer-center/issues/4021
=> fix: tray function lost

src/main/account.cpp, src/maincomponentplugin/article/Article.qml, src/maincomponentplugin/feedback/Submit.qml, src/maincomponentplugin/index/Index.qml, src/maincomponentplugin/maincomponent.qrc, src/maincomponentplugin/titlebar/MyTitleBar.qml
=> feat: add create feedback dialog

debian/changelog, src/dbusservice/com.deepin.Home.Daemon.xml, src/main/CMakeLists.txt, src/main/daemon.cpp, src/main/homeDaemon.cpp, src/main/homeDaemon.h, src/main/main.cpp, src/maincomponentplugin/feedback/Submit.qml, src/maincomponentplugin/router/Router.qml, src/maincomponentplugin/titlebar/TabButton.qml, translations/deepin-home.qrc, translations/deepin-home.ts, translations/deepin-home/az.ts, translations/deepin-home/ca.ts, translations/deepin-home/hu.ts, translations/deepin-home/nl.ts, translations/deepin-home/pl.ts, translations/deepin-home/uk.ts, translations/deepin-home/zh_CN.ts, translations/deepin-home/zh_HK.ts, translations/deepin-home/zh_TW.ts
Fixed List:
- https://github.com/linuxdeepin/developer-center/issues/4453
- https://github.com/linuxdeepin/developer-center/issues/4076
- https://github.com/linuxdeepin/developer-center/issues/4451
- https://github.com/linuxdeepin/developer-center/issues/4461
- https://github.com/linuxdeepin/developer-center/issues/4459
- https://github.com/linuxdeepin/developer-center/issues/4458
- https://github.com/linuxdeepin/developer-center/issues/4464
=> multiple small issues have been fixed

src/maincomponentplugin/feedback/List.qml, src/maincomponentplugin/feedback/Submit.qml, src/maincomponentplugin/index/Index.qml, src/maincomponentplugin/router/Router.qml, src/maincomponentplugin/titlebar/AccountButton.qml, src/maincomponentplugin/titlebar/TabButton.qml
修改菜单导航逻辑，在首页点击需求反馈，应该导航到需求广场，而不是弹出提交需求的对话框
=> feat: Home Page navigate to feedback hub

src/maincomponentplugin/api/API.qml, src/maincomponentplugin/feedback/Submit.qml, src/maincomponentplugin/worker.cpp, src/maincomponentplugin/worker.h
根据产品需求，在提交反馈时,上传系统的版本号,用于区分反馈场景，
有个提交是另一个 pr 的，需要先review https://github.com/linuxdeepin/deepin-home/pull/47
=> upload system version when submitting feedback 

CMakeLists.txt, debian/changelog, debian/control, src/main/CMakeLists.txt, src/main/main.cpp, src/maincomponentplugin/CMakeLists.txt, src/preloadplugin/CMakeLists.txt
=> feat: Support building on deepin v20

debian/changelog, src/maincomponentplugin/api/API.qml, src/maincomponentplugin/feedback/Detail.qml, src/maincomponentplugin/feedback/List.qml, src/maincomponentplugin/titlebar/TabButton.qml, translations/deepin-home.ts, translations/deepin-home/az.ts, translations/deepin-home/ca.ts, translations/deepin-home/fi.ts, translations/deepin-home/hu.ts, translations/deepin-home/nl.ts, translations/deepin-home/pl.ts, translations/deepin-home/uk.ts, translations/deepin-home/zh_CN.ts, translations/deepin-home/zh_HK.ts, translations/deepin-home/zh_TW.ts
在触发接口调用次数限制后,弹出操作过于频繁的提示,而不再显示网络错误页面
=> prompt the user when triggering API restrictions

debian/changelog, src/maincomponentplugin/api/API.qml, src/maincomponentplugin/feedback/Card.qml, src/maincomponentplugin/feedback/Status.qml, src/maincomponentplugin/feedback/Submit.qml
修复反馈的状态文本在某些状态字体颜色和背景色一样，导致不显示的问题
修复英文状态下，反馈的提交按钮显示异常，字母间距过大
=> fix: status text not display

README.md, README.zh_CN.md, src/maincomponentplugin/api/API.qml, src/maincomponentplugin/feedback/Card.qml, src/maincomponentplugin/feedback/Detail.qml, src/maincomponentplugin/feedback/List.qml, src/maincomponentplugin/worker.cpp, src/maincomponentplugin/worker.h
修复未登陆时无法查看截图
添加对gif动图播放的支持
点击截图时，使用看图工具查看截图而不是弹窗，看图工具有更多的图片操作支持
=> fix: Unable to view screenshot when not logged in 

debian/changelog, translations/deepin-home/hu.ts, translations/deepin-home/nl.ts, translations/deepin-home/pl.ts, translations/deepin-home/uk.ts, translations/deepin-home/zh_HK.ts, translations/deepin-home/zh_TW.ts
=> chore: Release 1.2.1

src/maincomponentplugin/api/API.qml
修复在我的反馈页面不显示截图,原因是未给图片拼接网址前缀
Issues: https://github.com/linuxdeepin/developer-center/issues/4903
=> fix: screenshots are not display on the 'My Feedback' page

src/maincomponentplugin/feedback/Card.qml
截图和按钮重叠显示
Log:
Issues: https://github.com/linuxdeepin/developer-center/issues/4930
=> fix: screenshot and buttons overlap

debian/control, src/CMakeLists.txt, src/dbusservice/com.deepin.Home.Daemon.xml, src/main/CMakeLists.txt, src/main/daemon.cpp, src/main/homeDaemon.cpp, src/main/homeDaemon.h, src/maincomponentplugin/CMakeLists.txt, src/maincomponentplugin/api/API.qml, src/maincomponentplugin/feedback/List.qml, src/maincomponentplugin/worker.cpp, src/maincomponentplugin/worker.h
保护用户token的安全,不允许其他应用调用getToken接口
使用非对称加密保护token不被监听
Log:
=> feat: Ensuring the security of user token

debian/changelog, src/dbusservice/com.deepin.Home.Daemon.xml, src/main/daemon.cpp, src/main/homeDaemon.cpp, src/main/homeDaemon.h, src/maincomponentplugin/worker.cpp
=> chore: Release 1.3.0

src/maincomponentplugin/feedback/Card.qml, src/maincomponentplugin/feedback/Detail.qml
回复内容可使用鼠标选择,便于复制回复的内容
Log:
Issues: https://github.com/linuxdeepin/developer-center/issues/4928
=> feat: Reply content can be selected by mouse

src/maincomponentplugin/CMakeLists.txt, src/maincomponentplugin/api/API.qml, src/maincomponentplugin/feedback/List.qml, src/maincomponentplugin/maincomponentplugin.cpp, src/maincomponentplugin/promise.cpp, src/maincomponentplugin/promise.h, src/maincomponentplugin/worker.cpp, src/maincomponentplugin/worker.h
=> feat: add promise support

src/maincomponentplugin/feedback/Card.qml, src/maincomponentplugin/feedback/List.qml, src/maincomponentplugin/feedback/Status.qml, src/maincomponentplugin/feedback/Submit.qml, src/maincomponentplugin/main.qml, src/maincomponentplugin/titlebar/AccountButton.qml, src/maincomponentplugin/titlebar/TabButton.qml
根据设计人员审查结果，调整界面细节
并修复Issues:
- https://github.com/linuxdeepin/developer-center/issues/5042
- https://github.com/linuxdeepin/developer-center/issues/5045
=> fine-tuning UI details

src/maincomponentplugin/feedback/Card.qml, src/maincomponentplugin/feedback/Detail.qml
1. fix feedback reply content wrap
2. fix feedback reply avatar
=> fix: feedback reply content wrap

src/maincomponentplugin/feedback/List.qml, src/maincomponentplugin/feedback/Submit.qml, src/maincomponentplugin/index/Index.qml, src/maincomponentplugin/main.qml, src/maincomponentplugin/router/Router.qml, src/maincomponentplugin/titlebar/AccountButton.qml, src/maincomponentplugin/titlebar/TabButton.qml
使用Repeater替换单Loader实现路由导航堆栈
在路由切换时缓存组件,可以避免回退时组件重新加载
Log:
Issues: https://github.com/linuxdeepin/developer-center/issues/5096
=> feat: add navigation stack support

src/maincomponentplugin/titlebar/MyTitleBar.qml
=> fix: Titlebar icon doesn't change with the theme

src/maincomponentplugin/feedback/Card.qml
修复官方回复内容能被编辑
Issues: https://github.com/linuxdeepin/developer-center/issues/5260
=> fix: Official replies can be edited

src/CMakeLists.txt, src/api/CMakeLists.txt, src/api/api.cpp, src/api/api.h, src/main/CMakeLists.txt, src/main/homeDaemon.cpp, src/maincomponentplugin/CMakeLists.txt, src/maincomponentplugin/feedback/Submit.qml, src/maincomponentplugin/router/Router.qml
=> feat: Extract the API into a standalone CMake module

src/maincomponentplugin/feedback/Submit.qml
=> feat: Content can be undone by Ctrl + Z when submitting feedback or requests

src/api/api.cpp, src/api/api.h, src/main/homeDaemon.cpp, src/maincomponentplugin/CMakeLists.txt, src/maincomponentplugin/apiproxy.cpp, src/maincomponentplugin/apiproxy.h, src/maincomponentplugin/list/Notify.qml, src/maincomponentplugin/list/Questionnaire.qml, src/maincomponentplugin/maincomponentplugin.cpp
=> feat: add api proxy component to qml

src/main/daemon.cpp, src/main/main.cpp, src/maincomponentplugin/apiproxy.cpp, src/maincomponentplugin/worker.cpp, translations/deepin-home-daemon.ts, translations/deepin-home.ts, translations/push
=> feat: The user token should not be print in the log

src/maincomponentplugin/apiproxy.cpp, src/maincomponentplugin/router/Router.qml, src/maincomponentplugin/titlebar/AccountButton.qml, src/maincomponentplugin/titlebar/TabButton.qml
修复在登出时没有返回到首页
在未登陆时点击我的反馈不进行跳转
修复我的收藏仅显示一页
Log:
Issues: https://github.com/linuxdeepin/developer-center/issues/5372
=> fix: not return to home page when logout

debian/changelog, src/maincomponentplugin/feedback/Submit.qml, translations/deepin-home.ts, translations/deepin-home/pl.ts, translations/deepin-home/zh_CN.ts
不同的反馈类型使用不同的提示文案
Log:
Issues: https://github.com/linuxdeepin/developer-center/issues/5000
=> fix: optimization tips content

src/maincomponentplugin/main.qml
给每个页面添加一个mouseArea做背景,避免鼠标穿透到下层页面
Log:
=> fix: page mouse event penetration

src/maincomponentplugin/feedback/Filter.qml, src/maincomponentplugin/feedback/List.qml
在反馈列表底部添加内间距,以实现更好的显示效果
Log:
Issues: https://github.com/linuxdeepin/developer-center/issues/6098
=> feat: Add padding to the bottom of the feedback list

3rdparty/apiserver/.openapi-generator/FILES, 3rdparty/apiserver/client/DHClientApi.cpp, 3rdparty/apiserver/client/DHClientApi.h, 3rdparty/apiserver/client/DHFeedback_CreateFeedbackRequest.cpp, 3rdparty/apiserver/client/DHFeedback_CreateFeedbackRequest.h, src/api/api.cpp, src/api/api.h, src/maincomponentplugin/apiproxy.cpp, src/maincomponentplugin/apiproxy.h, src/maincomponentplugin/feedback/Submit.qml, src/maincomponentplugin/worker.cpp, src/maincomponentplugin/worker.h
=> feat: support upload sysinfo

debian/changelog, debian/control, src/maincomponentplugin/feedback/Filter.qml, src/maincomponentplugin/feedback/List.qml, src/maincomponentplugin/feedback/Submit.qml, translations/deepin-home/ca.ts, translations/deepin-home/cs.ts, translations/deepin-home/es.ts, translations/deepin-home/fi.ts, translations/deepin-home/nl.ts, translations/deepin-home/pl.ts, translations/deepin-home/pt_BR.ts, translations/deepin-home/tr.ts, translations/deepin-home/uk.ts
无法筛选我的反馈
类型筛选下拉选项在英文环境显示不全
需求反馈不应该上传设备信息
=> fix: unable to filter my feedback

src/maincomponentplugin/feedback/List.qml
如果当前位于用户个人页面,比如我的反馈,我的收藏
在账号退出登陆时自动返回到首页
Log:
Issues: https://github.com/linuxdeepin/developer-center/issues/5661
=> feat: return to homepage when logged out

src/main/account.cpp
=> chore: correct a typo in account.cpp

src/dbusservice/com.deepin.Home.Daemon.xml, src/main/daemon.cpp, src/main/homeDaemon.cpp, src/main/homeDaemon.h, src/main/main.cpp, src/maincomponentplugin/feedback/Submit.qml, src/maincomponentplugin/worker.cpp, src/maincomponentplugin/worker.h
优化邮件输入框的用户体验
Log:
Issues: https://github.com/linuxdeepin/developer-center/issues/6430
=> feat: Improve user experience for email input field

src/maincomponentplugin/feedback/List.qml
反馈详情中的收藏统计显示错误
Log:
Issues: https://github.com/linuxdeepin/developer-center/issues/5451
=> fix: collect count of feedback detail display incorrectly

debian/changelog, debian/control
添加缺失的依赖
Log:
Issues: https://github.com/linuxdeepin/developer-center/issues/7036
=> feat: add qt quick layouts to depends

.gitignore, .reuse/dep5, deepin-home-daemon.desktop, deepin-home.desktop, linglong.yaml, src/CMakeLists.txt, src/dbusservice/com.deepin.Home.Daemon.service, src/dbusservice/com.deepin.Home.Daemon.service.in, src/main/CMakeLists.txt
=> feat: add linglong build support

debian/changelog, src/CMakeLists.txt
=> feat: change dtk qml app plugin path

debian/changelog, src/main/homeDaemon.cpp, src/main/homeDaemon.h, src/maincomponentplugin/worker.cpp
修复频繁点击托盘图标导致客户端卡死的问题
修复apt源信息缺少部分内容
Issues: https://github.com/linuxdeepin/developer-center/issues/8460
Issues: https://github.com/linuxdeepin/developer-center/issues/8188
=> chore: Release 1.5.10

debian/changelog
=> chore: Release 1.6.3
